/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.smarthome.model.sitemap.standard.ide


/**
 * Use this class to register ide components.
 */
class SmartHomeSitemapIdeModule extends AbstractSmartHomeSitemapIdeModule {
}
