/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.smarthome.model.sitemap.standard


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SmartHomeSitemapRuntimeModule extends AbstractSmartHomeSitemapRuntimeModule {
}
